## NumPy 

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

  - a powerful N-dimensional array object
  - sophisticated (broadcasting) functions
  - tools for integrating C/C++ and Fortran code
  - useful linear algebra, Fourier transform, and random number capabilities

In [1]:
import numpy as np

# PART 1 - Intro to Arrays in NumPy

Numpy has a ton of built-in functions that are useful for Data Scientists & Python Programmers alike.

We shall cover some of the most important topics in Numpy: 

  - Arrays ( using Vectors & Matrices ) 
  - Number Generation Concepts

# Numpy Arrays

NumPy arrays are the one of the most widely used data structuring techniques by Data Scientists. 

Numpy arrays are of two types: Vectors and Matrices. 

Vectors are 1-dimensional arrays and matrices are 2-dimensional arrays(A Matrix can still possess a single row or a column).

We shall begin our learning with how to create NumPy Arrays.

## Creating simple NumPy Array Structures

We could create a simple Array by using a list of values or a list of "List of values".

In [2]:
simple_list = [101,102,103,104,105,106,107,108,109,110]
simple_list

[101, 102, 103, 104, 105, 106, 107, 108, 109, 110]

In [3]:
np.array(simple_list)

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [4]:
simple_list_of_lists = [[10,11,12],[20,21,22],[30,31,32]]
simple_list_of_lists

[[10, 11, 12], [20, 21, 22], [30, 31, 32]]

In [5]:
np.array(simple_list_of_lists)

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

**There are multiple built-in methods to generate Arrays**

### arange

Return evenly spaced values within a given interval as input.

In [6]:
#np.arange(0,20)        
# Return values 0 to 19. Start value is 0 which is included, the stop value provided is 20 which is not included
np.arange(0,20)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
#np.arange(0,20,4)       # Specify start, stop and step values as 
np.arange(0,20,5)

array([ 0,  5, 10, 15])

### 0's and 1's

Generate arrays of 0's or 1's

In [8]:
#np.zeros(10)            # Specify the count of 0's required in the array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
#np.zeros((4,3))         # Specify the number of rows by columns - 4 rows and 3 cols in this example
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## eye

Return a 2-D array with ones on the diagonal and zeros elsewhere. Also called an identity matrix

In [10]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random 

Numpy has lots of options to create random numbered arrays:

### rand
Create an array of the given shape and populate it with random variables derived from a uniform distribution between `[0, 1)`.

In [15]:
#np.random.rand(5)
np.random.rand(5)

array([0.54041691, 0.17064178, 0.61911055, 0.74542156, 0.78658573])

In [17]:
#np.random.rand(3,2)
np.random.rand(3,2)

array([[0.63738459, 0.2214712 ],
       [0.98309705, 0.055426  ],
       [0.83683867, 0.21023217]])

### randn

Return a variable (or a set of variables) from the "Standard Normal" distribution. Unlike rand which is from a uniform distribution: 

A standard Normal Distribution has mean 0 and SD of 1 as we know.

In [18]:
np.random.randn(5)

array([ 1.2925945 ,  0.03467052,  0.1581446 , -0.28420237, -1.48522955])

In [19]:
np.random.randn(3,2)

array([[ 1.26144696,  0.1181187 ],
       [ 0.37557553, -0.2795225 ],
       [-1.92880938,  0.5440596 ]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [20]:
np.random.randint(5,20)       # Returns one rand integer between the values 5 & 19(20 is excluded)

12

In [21]:
np.random.randint(20,50,5)  # Returns  5 rand integers between 20 & 49(50 is excluded)

array([32, 40, 48, 49, 47])

## Array Attributes and Methods for an array

Let us look at some important attributes and methods for an array.

In [42]:
sample_array = np.arange(30)
rand_array = np.random.randint(0,100,20)

In [43]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [44]:
rand_array

array([17, 67, 94, 76, 89, 17, 53,  8, 50, 27, 22, 81, 12, 50, 55, 67, 68,
       68, 71, 96])

## Reshape
Returns an array containing the same data with a new shape.

In [25]:
#sample_array.reshape(5,6)
sample_array.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [45]:
rand_array

array([17, 67, 94, 76, 89, 17, 53,  8, 50, 27, 22, 81, 12, 50, 55, 67, 68,
       68, 71, 96])

In [27]:
rand_array.max()

97

In [28]:
rand_array.argmax()

2

In [29]:
#rand_array.min()
rand_array.min()

6

In [51]:
rand_array.sort(axis=0)
rand_array

array([ 8, 12, 17, 17, 22, 27, 50, 50, 53, 55, 67, 67, 68, 68, 71, 76, 81,
       89, 94, 96])

## Shape

Shape is an attribute that arrays have. It is not a method.

In [55]:
# Vector
#sample_array.shape
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [54]:
# Output has two sets of brackets - which indicates a matrix and not a vector
sample_array.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [56]:
sample_array.reshape(1,30).shape

(1, 30)

In [ ]:
sample_array.reshape(30,1)

In [ ]:
sample_array.reshape(30,1).shape

### dtype

You could retrieve the data type of the object in an array using dtype.

In [57]:
sample_array.dtype

dtype('int64')

In [58]:
sample_array.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

# Part 2 - NumPy Indexing & Selection

We will now learn how to select objects or groups of objects from an array

In [ ]:
sample_array

In [59]:
sample_array[8]

8

In [69]:
#Get values from a range selection
sample_array[:3]

array([0, 1, 2])

In [61]:
#Get values from specific index positions
sample_array[[0,4,7]]

array([0, 4, 7])

## Indexing a Matrix - 2 dimensional arrays

The general formats used are 

**sample_matrix[row][col]** 

or

**sample_matrix[row,col]**

We will use the second option as standard.

In [65]:
sample_matrix = np.array(([50,200,5,10],[10,35,50,15],[25,100,145,120],[105,25,65,80]))

#Show output
sample_matrix

array([[ 50, 200,   5,  10],
       [ 10,  35,  50,  15],
       [ 25, 100, 145, 120],
       [105,  25,  65,  80]])

In [66]:
#Indexing rows
sample_matrix[1]


array([10, 35, 50, 15])

In [67]:
# Getting an individual element value from the matrix - Method 1
sample_matrix[1][2]

50

In [68]:
# Slicing matrix

#Shape (3,3) from top right corner
sample_matrix[:3,1:]

array([[200,   5,  10],
       [ 35,  50,  15],
       [100, 145, 120]])

In [70]:
sample_matrix[1:3,1:]

array([[ 35,  50,  15],
       [100, 145, 120]])

In [71]:
#Shape bottom row - Including column selection (Alternate to above)
sample_matrix[3,:]

array([105,  25,  65,  80])

## Selection

Using brackets for selection based on operators for comparison

In [72]:
simple_array = np.arange(1,31)
simple_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [73]:
simple_array <10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [74]:
boolean_array = simple_array<10
boolean_array

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [75]:
simple_array[boolean_array]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
simple_array[simple_array>15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [77]:
a = 11
simple_array[simple_array>a]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30])

In [80]:
bool = simple_array>a

In [81]:
bool

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])